server:
  port: 8080

logging:
  level.io.fdlessard.codebites.oauth2.authorization: DEBUG
  level.root: DEBUG

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: de5c5667babc12b55474
      client-secret: 5b95cc5c48d09a18570f6a9f1be3b6d9a86efc7b
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      token-info-uri: https://github.com/login/oauth/check_token
      userInfoUri: https://api.github.com/fdlessard
