server:
  port: 8081

logging:
  level.io.fdlessard.codebites.oauth2.authorization: DEBUG
  level.root: DEBUG

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
#      scope: all
#      authorized-grant-types: authorization_code,refresh_token,password
      access-token-validity-seconds: 3600
      refresh-token-validity-seconds: 3600
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:db;MODE=PostgreSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true